---
refresh_interval: 3
retry_interval: 5
pages:
  "com.apple.finder":
    buttons:
      - position: [1, 1]
        label: Applications
        image:
          provider: fontawesome
          path: brands/apple.svg
        action:
          hotkeys: shift|command|a
      - position: [1, 2]
        label: Downloads
        image:
          provider: fontawesome
          path: solid/download.svg
        action:
          hotkeys: option|command|l
  "com.microsoft.VSCode":
    buttons:
      - position: [1, 1]
        label: VSCode
        image:
          provider: file
          path: vscode.png
        action:
          hotkeys: f1
      - position: [1, 2]
        label: Search
        image:
          provider: fontawesome
          path: solid/magnifying-glass.svg
        action:
          hotkeys: command|shift|f
      - position: [3, 2]
        label: Time
        image:
          provider: function
          function: time_display()
        action:
          hotkeys: win
  "co.zeit.hyper":
    buttons:
      - position: [1, 1]
        label: Hyper
        image:
          provider: fontawesome
          path: solid/terminal.svg
        action:
          hotkeys: f1
      - position: [1, 2]
        label: Search
        image:
          provider: fontawesome
          path: solid/magnifying-glass.svg
        action:
          hotkeys: command|f
      - position: [2, 1]
        label: Copy
        image:
          provider: fontawesome
          path: solid/copy.svg
        action:
          hotkeys: command|c
      - position: [2, 2]
        label: Paste
        image:
          provider: fontawesome
          path: solid/paste.svg
        action:
          hotkeys: command|v
  "com.apple.Safari":
    buttons:
      - position: [1, 1]
        label: Safari
        image:
          provider: file
          path: safari.png
        action:
          hotkeys: f1
  "org.mozilla.firefox":
    buttons:
      - position: [1, 1]
        label: Firefox
        image:
          provider: file
          path: firefox.png
        action:
          hotkeys: f1
  "com.apple.Photos":
    buttons:
      - position: [1, 2]
        label: Add Fav
        image:
          provider: fontawesome
          path: solid/heart.svg
        action:
          hotkeys: .
