---
refresh_interval: 3
retry_interval: 5
display_label: False
action_triggers:
  freeze_page: [[1, 1], [1, 5]]
  reload_config: [[1, 1], [3, 1]]
image_providers:
  file:
    path: assets/pages
  fontawesome:
    path: assets/vendor/fontawesome/svgs
    inverted: true
  fluentui-emoji:
    path: assets/vendor/fluentui-emoji/assets
  google-cloud-icons:
    path: assets/vendor/google-cloud-icons
pages:
  "com.apple.finder":
    buttons:
      - position: [1, 1]
        label: Applications
        image:
          provider: fontawesome
          path: brands/apple.svg
        actions:
          short:
            type: hotkeys
            instruction: shift+command+a
          long:
            type: hotkeys
            instruction: shift+command+h
      - position: [1, 2]
        label: Downloads
        image:
          provider: fontawesome
          path: solid/download.svg
        actions:
          short:
            type: hotkeys
            instruction: option+command+l
  "com.microsoft.VSCode":
    buttons:
      - position: [1, 1]
        label: VSCode
        image:
          provider: file
          path: vscode.png
        actions:
          short:
            type: hotkeys
            instruction: f1
      - position: [1, 2]
        label: Search
        image:
          provider: fontawesome
          path: solid/magnifying-glass.svg
        actions:
          short:
            type: hotkeys
            instruction: shift+command+f
      - position: [3, 2]
        label: Time
        image:
          provider: function
          function: time_display()
        actions:
          short:
            type: hotkeys
            instruction: f1
  "co.zeit.hyper":
    buttons:
      - position: [1, 1]
        label: Hyper
        image:
          provider: fontawesome
          path: solid/terminal.svg
        actions:
          short:
            type: hotkeys
            instruction: f1
      - position: [1, 2]
        label: Search
        image:
          provider: fontawesome
          path: solid/magnifying-glass.svg
        actions:
          short:
            type: hotkeys
            instruction: command+f
      - position: [2, 1]
        label: Copy
        image:
          provider: fontawesome
          path: solid/copy.svg
        actions:
          short:
            type: hotkeys
            instruction: command+c
      - position: [2, 2]
        label: Paste
        image:
          provider: fontawesome
          path: solid/paste.svg
        actions:
          short:
            type: hotkeys
            instruction: command+v
  "com.apple.Safari":
    buttons:
      - position: [1, 1]
        label: Safari
        image:
          provider: file
          path: safari.png
        actions:
          short:
            type: hotkeys
            instruction: f1
  "org.mozilla.firefox":
    buttons:
      - position: [1, 1]
        label: Firefox
        image:
          provider: file
          path: firefox.png
        actions:
          short:
            type: hotkeys
            instruction: f1
  "com.apple.Photos":
    buttons:
      - position: [1, 2]
        label: Add Fav
        image:
          provider: fontawesome
          path: solid/heart.svg
        actions:
          short:
            type: hotkeys
            instruction: .
